/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_carconfig_free(a: number): void;
export function __wbg_get_carconfig_angle(a: number): number;
export function __wbg_set_carconfig_angle(a: number, b: number): void;
export function __wbg_get_carconfig_angle_delta(a: number): number;
export function __wbg_set_carconfig_angle_delta(a: number, b: number): void;
export function carconfig_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_car_free(a: number): void;
export function __wbg_get_car_x(a: number): number;
export function __wbg_set_car_x(a: number, b: number): void;
export function __wbg_get_car_y(a: number): number;
export function __wbg_set_car_y(a: number, b: number): void;
export function __wbg_get_car_width(a: number): number;
export function __wbg_set_car_width(a: number, b: number): void;
export function __wbg_get_car_height(a: number): number;
export function __wbg_set_car_height(a: number, b: number): void;
export function __wbg_get_car_config(a: number): number;
export function __wbg_set_car_config(a: number, b: number): void;
export function __wbg_get_car_control(a: number): number;
export function __wbg_set_car_control(a: number, b: number): void;
export function car_withConfig(a: number, b: number): number;
export function car_new(a: number, b: number, c: number, d: number): number;
export function car_get_forward(a: number): number;
export function car_get_left(a: number): number;
export function car_get_right(a: number): number;
export function car_get_reverse(a: number): number;
export function car_set_forward(a: number, b: number): void;
export function car_set_left(a: number, b: number): void;
export function car_set_right(a: number, b: number): void;
export function car_set_reverse(a: number, b: number): void;
export function __wbg_control_free(a: number): void;
export function control_get_forward(a: number): number;
export function control_get_left(a: number): number;
export function control_get_right(a: number): number;
export function control_get_reverse(a: number): number;
export function car_update(a: number): void;
export function car_draw(a: number, b: number): void;
export function __wbg_get_carconfig_speed(a: number): number;
export function __wbg_get_carconfig_acceleration(a: number): number;
export function __wbg_get_carconfig_max_speed(a: number): number;
export function __wbg_get_carconfig_friction(a: number): number;
export function __wbg_set_carconfig_speed(a: number, b: number): void;
export function __wbg_set_carconfig_acceleration(a: number, b: number): void;
export function __wbg_set_carconfig_max_speed(a: number, b: number): void;
export function __wbg_set_carconfig_friction(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_exn_store(a: number): void;
