name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install wasm-pack, clippy, nextest, and tarpaulin.
      run: cargo install wasm-pack clippy nextest tarpaulin
    - name: Run tests
      run: cargo nextest run --release --verbose
    - name: Generate test coverage report.
      run: cargo tarpaulin -o Html --output-dir ./target/tarpaulin
    - name: Run rustfmt
      run: rustfmt src/**/*.rs --config-path ./Cargo.toml
    - name: Run clippy
      run: cargo clippy --no-deps --fix
    - name: Compile into wasm.
      run: wasm-pack build --target web --release --out-dir ./public/web
    - name: Archive production build.
      uses: actions/upload-artifact@v3
      with:
        name: production-static-files
        path: |
          public
    - name: Archive code coverage results.
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage-report
        path: |
          target/tarpaulin
